# Generated by Django 2.2.9 on 2020-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='key_words',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
