# Generated by Django 2.2.9 on 2020-01-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200108_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
