# Generated by Django 2.2.9 on 2020-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contributor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='key_words',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
