# Generated by Django 2.2.9 on 2020-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200108_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='key_words',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
