# Generated by Django 2.2.9 on 2020-01-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200108_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='author',
        ),
    ]
