# Generated by Django 2.2.9 on 2020-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contributor_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contribution',
            field=models.CharField(choices=[('TALK', 'Talk'), ('POSTER', 'Poster')], default='TALK', max_length=2),
        ),
    ]
