# Generated by Django 2.2.9 on 2020-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200314_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='bio',
            field=models.TextField(default='', verbose_name='Short Biography'),
        ),
    ]
