# Generated by Django 2.2.9 on 2020-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200314_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='citytour',
            field=models.BooleanField(default=False, verbose_name='I am joining the guided city tour (FREE - Thursday 5th of November)'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='restaurant',
            field=models.BooleanField(default=False, verbose_name='I am joining the social dinner on Thursday 5th of November'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='welcome',
            field=models.BooleanField(default=False, verbose_name='I am joining the welcome evening (Wednesday 4th of November)'),
        ),
    ]
